homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 13
  unit_system: metric
  time_zone: UTC
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
    - type: homeassistant

recorder:
  db_url: !secret db_url
  purge_keep_days: 3650
  exclude:
    entities:
      - persistent_notification.config_entry_discovery
      - persistent_notification.httplogin
      - persistent_notification.http_login
      - persistent_notification.homeassistantcheck_config
      - device_tracker.google_maps_113979464641038639988
      - light.group_for_wakeup
      - light.bedroom_hue_color_lamp
      - light.study_hue_color_lamp
      - zone.home
      - group.all_devices
      - updater.updater

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
#   base_url: example.duckdns.org:8123
   api_password: !secret appdaemon_token


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor: !include sensors.yaml

switch: !include switches.yaml


device_tracker:
  - platform: google_maps
    username: !secret dev_email
    password: !secret dev_password

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
