homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 13
  unit_system: metric
  time_zone: UTC
  customize: !include customize.yaml
  auth_providers:
#    - type: legacy_api_password
    - type: homeassistant

lovelace:
  mode: yaml

recorder:
  db_url: !secret db_url
  purge_keep_days: 3650
  exclude:
    entities:
      - persistent_notification.config_entry_discovery
      - persistent_notification.httplogin
      - persistent_notification.http_login
      - persistent_notification.homeassistantcheck_config
      - persistent_notification.invalid_config
      - device_tracker.google_maps_113979464641038639988
      - light.group_for_wakeup
      - light.bedroom_hue_color_lamp
      - light.study_hue_color_lamp
      - zone.home
      - group.all_devices
      - updater.updater
      - switch.deluge_switch
      - sensor.deluge_status
      - binary_sensor.prusa_i3_mk3_printing
      - binary_sensor.prusa_i3_mk3_printing_error
      - group.all_lights
      - light.hue_color_lamp_2
      - light.hue_color_lamp_1
      - sun.sun

tts:
  - platform: google

#http:
#  api_password: !secret appdaemon_token

# ==================== OctoPrint ==================== #

#octoprint:
#  host: !secret octoprint_host
#  api_key: !secret octoprint_api_key
#  name: Prusa i3 Mk3
#  bed: true
#  number_of_tools: 1

#camera:
#  - platform: mjpeg
#    name: Prusa i3 Mk3
#    still_image_url: !secret octoprint_snapshot
#    mjpeg_url: !secret octoprint_stream


mqtt:
  broker: !secret mqtt_host

updater:
frontend:
config:
discovery:
conversation:
history:
logbook:
map:
sun:
cloud:
system_health:

sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
