homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 13
  unit_system: metric
  time_zone: UTC
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant

lovelace:
  mode: yaml

recorder:
  db_url: !secret db_url
  purge_keep_days: 3650
  exclude:
    entities:
      - persistent_notification.config_entry_discovery
      - persistent_notification.httplogin
      - persistent_notification.http_login
      - persistent_notification.homeassistantcheck_config
      - persistent_notification.invalid_config
      - device_tracker.google_maps_113979464641038639988
      - light.group_for_wakeup
      - light.bedroom_hue_color_lamp
      - light.study_hue_color_lamp
      - zone.home
      - group.all_devices
      - updater.updater
      - switch.deluge_switch
      - sensor.deluge_status
      - binary_sensor.prusa_i3_mk3_printing
      - binary_sensor.prusa_i3_mk3_printing_error
      - group.all_lights
      - light.hue_color_lamp_2
      - light.hue_color_lamp_1
      - sun.sun
      - camera.prusa_i3_mk3
      - persistent_notification.homeassistant_check_config
      - sensor.custom_component_tracker
      - binary_sensor.remote_ui
      - sensor.habitica_worgarside_name
      - light.greenhouse

tts:
  - platform: google_translate

panel_iframe:
  octoprint:
    title: 'OctoPrint'
    url: 'http://192.168.1.3'
    icon: 'mdi:printer-3d'

frontend:
  themes: !include lovelace/themes.yaml


http:
  base_url: !secret base_url
  cors_allowed_origins: !secret cors_allowed_origins

media_player:
  - platform: plex
    use_episode_art: true
    entity_namespace: plex
  - platform: braviatv
    host: !secret bravia_ip

# ==================== OctoPrint ==================== #

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  name: Prusa i3 Mk3
  bed: true
  number_of_tools: 1

habitica:
  - api_user: !secret habitica_user
    api_key: !secret habitica_key
    name: !secret habitica_name

camera:
  - platform: mjpeg
    name: Prusa i3 Mk3
    still_image_url: !secret octoprint_snapshot
    mjpeg_url: !secret octoprint_stream

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

mqtt:
  broker: !secret mqtt_host

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

updater:
config:
discovery:
conversation:
history:
logbook:
map:
sun:
cloud:
system_health:

sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
