- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - temperature

- platform: ee

- platform: google_fit

- platform: my_fitness_pal

- platform: uptime
  name: Time Online
  unit_of_measurement: hours

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: cpuspeed
  name: CPU Speed

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2)  }}'