- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - temperature

- platform: uptime
  name: Time Online
  unit_of_measurement: hours

- platform: deluge
  host: !secret datapi_host
  username: !secret deluge_username
  password: !secret deluge_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

# ==================== Custom Sensors ==================== #

- platform: ee

- platform: google_fit

- platform: strava

- platform: hass_stats

- platform: monzo

# ==================== MQTT ==================== #

# ------------------- Prusa DHT_22 ------------------- #

- platform: mqtt
  name: "Prusa Mk3 Ambient Temperature"
  state_topic: !secret prusa_temp_humid_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Prusa Mk3 Ambient Humidity"
  state_topic: !secret prusa_temp_humid_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"

# ------------------- OctoPi ------------------- #

- platform: mqtt
  name: "OctoPi CPU Temp"
  state_topic: !secret octopi_stats_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "OctoPi Disk Usage"
  state_topic: !secret octopi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.disk_usage_percent }}"

- platform: mqtt
  name: "OctoPi Memory Usage"
  state_topic: !secret octopi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.memory_usage }}"

- platform: mqtt
  name: "OctoPi CPU Usage"
  state_topic: !secret octopi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.cpu_usage }}"

- platform: mqtt
  name: "OctoPi Load (15m)"
  state_topic: !secret octopi_stats_mqtt_topic
  unit_of_measurement: ' '
  value_template: "{{ value_json.load_15m }}"

# ------------------- HassPi ------------------- #

- platform: mqtt
  name: "HAssPi CPU Temp"
  state_topic: !secret hasspi_stats_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "HAssPi Disk Usage"
  state_topic: !secret hasspi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.disk_usage_percent }}"

- platform: mqtt
  name: "HAssPi Memory Usage"
  state_topic: !secret hasspi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.memory_usage }}"

- platform: mqtt
  name: "HAssPi CPU Usage"
  state_topic: !secret hasspi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.cpu_usage }}"

- platform: mqtt
  name: "HAssPi Load (15m)"
  state_topic: !secret hasspi_stats_mqtt_topic
  unit_of_measurement: ' '
  value_template: "{{ value_json.load_15m }}"

# ------------------- DataPi ------------------- #

- platform: mqtt
  name: "DataPi CPU Temp"
  state_topic: !secret datapi_stats_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "DataPi Disk Usage"
  state_topic: !secret datapi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.disk_usage_percent }}"

- platform: mqtt
  name: "DataPi Memory Usage"
  state_topic: !secret datapi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.memory_usage }}"

- platform: mqtt
  name: "DataPi CPU Usage"
  state_topic: !secret datapi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.cpu_usage }}"

- platform: mqtt
  name: "DataPi Load (15m)"
  state_topic: !secret datapi_stats_mqtt_topic
  unit_of_measurement: ' '
  value_template: "{{ value_json.load_15m }}"

# ------------------- CRT-Pi ------------------- #

- platform: mqtt
  name: "CRT-Pi CPU Temp"
  state_topic: !secret crt-pi_stats_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "CRT-Pi Disk Usage"
  state_topic: !secret crt-pi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.disk_usage_percent }}"

- platform: mqtt
  name: "CRT-Pi Memory Usage"
  state_topic: !secret crt-pi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.memory_usage }}"

- platform: mqtt
  name: "CRT-Pi CPU Usage"
  state_topic: !secret crt-pi_stats_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.cpu_usage }}"

- platform: mqtt
  name: "CRT-Pi Load (15m)"
  state_topic: !secret crt-pi_stats_mqtt_topic
  unit_of_measurement: ' '
  value_template: "{{ value_json.load_15m }}"
