- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - temperature

- platform: ee

- platform: google_fit

- platform: my_fitness_pal

- platform: strava

- platform: uptime
  name: Time Online
  unit_of_measurement: hours

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2)  }}'

#- platform: deluge
#  host: 192.168.1.2
#  username: !secret deluge_username
#  password: !secret deluge_password
#  monitored_variables:
#    - 'current_status'
#    - 'download_speed'
#    - 'upload_speed'

- platform: mqtt
  name: "Prusa Mk3 Ambient Temperature"
  state_topic: !secret prusa_temp_humid_mqtt_topic
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Prusa Mk3 Ambient Humidity"
  state_topic: !secret prusa_temp_humid_mqtt_topic
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"