title: 15 Robins Court

resources:
  - url: /customcards/bignumber-card.js?v=1
    type: js
  - url: /customcards/vertical-stack-in-card.js?v=0.1.1
    type: js
  - url: /customcards/dual-gauge-card.js?v=1?track=true
    type: js
  - url: /customcards/mini-graph-card-bundle.js
    type: module
  - url: /customcards/tracker-card.js
    type: js
  - type: css
    url: 'https://fonts.googleapis.com/css?family=Raleway'
  - url: /customcards/compact-custom-header.js?v=0.0.1
    type: module

background: center / cover no-repeat url("/local/light_bg_2.jpg") fixed

views:
  - !include lovelace/home.yaml
  - !include lovelace/makerspace.yaml
  - !include lovelace/pi_monitoring.yaml
  - !include lovelace/admin.yaml