title: 15 Robins Court

resources:
  - url: /local/bignumber-card.js?v=1
    type: js
  - url: /local/vertical-stack-in-card.js?v=0.1.1
    type: js
  - url: /local/dual-gauge-card.js?v=1?track=true
    type: js
  - url: /local/mini-graph-card-bundle.js
    type: module
  - url: /local/tracker-card.js
    type: js
  - url: /local/compact-custom-header.js?v=0.0.1
    type: module

background: center / cover no-repeat url("/local/light_bg_3.jpg") fixed

views:
  - !include lovelace/home.yaml
  - !include lovelace/makerspace.yaml
  - !include lovelace/pi_monitoring.yaml
  - !include lovelace/admin.yaml